site_name: Max Young Project Centre
theme:
  name: material
  palette:
    primary: blue
  features:
    - content.code.copy

nav:
    - Home: index.md
    # - About: about.md
    # - KGM: https://gyrohammer.github.io/KGM

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: True
      
repo_url: https://github.com/Gyrohammer/gyrohammer.github.io
repo_name: gyrohammer/gyrohammer.github.io